plugins {
    id 'java-library'
    id 'io.spring.dependency-management'
}

dependencies {
    implementation project(':takibo-outbox-spring-starter')
    implementation project(':takibo-outbox-jpa')
    implementation project(':takibo-outbox-core')

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'com.icegreen:greenmail:2.1.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
