package com.takibo.securitymanagement.sentinel.advice;

public enum SentinelErrorCode {
    // SECURITY (401/403)
    INVALID_TOKEN,
    AUTHENTICATION_FAILED,
    BAD_CREDENTIALS,
    ACCESS_DENIED,
    ACCOUNT_LOCKED,
    USER_NOT_MEMBER_OF_SPACE,
    USER_NOT_ACTIVE,

    // OAUTH2 / AUTHORIZATION SERVER
    OAUTH2_INVALID_REQUEST,
    OAUTH2_INVALID_CLIENT,
    OAUTH_CLIENT_ALREADY_EXISTS,
    TENANT_RESOLUTION_FAILED,

    // USERS
    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    PASSWORD_POLICY_VIOLATION,
    NON_UNIQUE_RESULT,
    USER_CREATION_ERROR,
    INVALID_STATUS_TRANSITION,

    // ORGANIZATIONS
    ORGANIZATION_NOT_FOUND,

    // RBAC CATALOG
    ROLE_NOT_FOUND,
    GROUP_NOT_FOUND,
    PERMISSION_NOT_FOUND,

    // SPACES
    SPACE_DISABLED,
    SPACE_SUSPENDED,
    SPACE_STATUS_UNKNOWN,
    SPACE_NOT_FOUND,
    SPACE_NOT_ACTIVE,

    // VALIDATION
    BAD_REQUEST,
    OAUTH_CLIENT_PROFILE_INVALID,

    // GENERIC
    INTERNAL_ERROR
}
