plugins {
    id 'java-library'
    id 'io.spring.dependency-management'
}

dependencies {
    api project(':takibo-adp-api')
    api project(':takibo-adp-core')

    implementation project(':takibo-security-context')
    implementation project(':takibo-security-context-spring')

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework:spring-web'

    compileOnly 'jakarta.servlet:jakarta.servlet-api'
    compileOnly 'org.springframework.data:spring-data-jpa'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}