plugins {
    id 'java-library'
    id 'io.spring.dependency-management'
}

dependencies {
    implementation project(':takibo-outbox-core')
    implementation project(':takibo-outbox-jpa')

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework:spring-tx'
    implementation 'com.fasterxml.jackson.core:jackson-annotations'
    compileOnly 'org.mapstruct:mapstruct:1.6.3'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
