-- === Takibu Audit : table principale (fusion CREATE + ALTER) ===

CREATE TABLE audit_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    audit_type    VARCHAR(50)  NOT NULL,
    entity_type   VARCHAR(100) NOT NULL,
    entity_id     VARCHAR(500),

    user_id       VARCHAR(100),
    actor_account_id VARCHAR(100),
    actor_user_id    VARCHAR(100),

    org_id        VARCHAR(100),
    space_id      VARCHAR(100),

    actor_type    VARCHAR(50),
    actor_source  VARCHAR(100),

    action        VARCHAR(255),
    status        VARCHAR(20),

    error         TEXT,
    details       TEXT,

    params        JSON NOT NULL,
    trace_id      VARCHAR(50),
    client_ip     VARCHAR(50),
    user_agent    VARCHAR(255),
    client_app    VARCHAR(100),

    duration_ms   BIGINT,
    http_method   VARCHAR(50),
    endpoint      VARCHAR(500)
);

-- Index fonctionnels
CREATE INDEX ix_audit_event_ts
    ON audit_event (timestamp);

CREATE INDEX ix_audit_event_type
    ON audit_event (audit_type);

CREATE INDEX ix_audit_event_trace
    ON audit_event (trace_id);

CREATE INDEX ix_audit_event_entity
    ON audit_event (entity_type, entity_id);

-- Optionnel (multi-tenant queries)
CREATE INDEX ix_audit_event_org_space
    ON audit_event (org_id, space_id);
