spring:
  mail:
    host: localhost
    port: 1025
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

takibo:
  messaging:
    catalog:
      messages:
        AUDIT_SECURITY_ALERT:
          from: security@takibu-iam.com
          recipients:
            - dev-team@takibu.com
