spring:
  datasource:
    password:

  mail:
    host: smtp.gmail.com
    port: 587
    username: change-me
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

takibo:
  messaging:
    catalog:
      messages:
        WELCOME_SPACE:
          from: no-reply@example.com
          recipients:
            - user@example.com
        AUDIT_SECURITY_ALERT:
          from: alerts@example.com
          recipients:
            - admin@example.com

